### ISSUE TITLE
Chosing a specific version of "vendored" botan

### ISSUE THREAD

**Issue by ncoder-1** [randombit/botan-rs#117]
Hi,

I was doing a test run of `botan-rs` (0.10.7) using `--feature vendored` and noticed it built botan version 3.1.1 according to the output of:

```
Version { major: 3, minor: 1, patch: 1, release_date: 0, ffi_api: 20230711, string: "Botan 3.1.1 (unreleased, revision unknown, distribution https://crates.io/crates/botan-src)" }
```

But if I use `--feature botan3`, it will, as expected, use my system's provided botan3 which is 3.2.0.

```
Version { major: 3, minor: 2, patch: 0, release_date: 20231009, ffi_api: 20231009, string: "Botan 3.2.0 (release, dated 20231009, revision git:6f466a2704a31856ebc27451ca861527d3dd00a1, distribution unspecified)" }
```

Is there a way to pick the `vendored` botan3 lib or are they tied by crate release?

**Comment by randombit** [comment]
Sorry about the delay in replying to this. Currently there is no way to selected the vendored version; it just takes whatever the submodule points to. Ideally, the submodule would always point to the latest release since there is no reason I know of to prefer an older version. However until quite recently `botan-src` was quite out of date in this respect. I'm looking at ways to make this cleaner (#102)
