### ISSUE TITLE
Download botan while building

### ISSUE THREAD

**Issue by dariusc93** [randombit/botan-rs#14]
While users could simply download botan via package manager on their system, It probably wont be as reliable. Cannot really comment on windows, but on most linux distributions, the library is not always up to date or using a stable release that would be compatible with this binding. As a suggestion, I think it might be better to download whats needed while building with this crate to make it easier for developers and maybe have something to allow users to override it so they could use whats on the system or a custom path to a specific botan build.

**Comment by randombit** [comment]
I think it's important to have an option to be able to use the system provided (or otherwise externally created) install of the library. But yeah many older distros ship something < 2.8.0 so having the ability to build a release via build.rs sounds good. In that case we could even configure the library for optimum use from the Rust crate, eg TLS isn't supported in the C89 layer right now, so there is no need to build TLS into the library itself because we know that a Rust crate could never invoke it.

**Comment by randombit** [comment]
This has been done in #15 and is available in the 0.7.0 release. If you have any problems using it please open a new issue. Thanks!
