### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by est31** [randombit/botan-rs#16]
It would be great if one would have nicer errors. I'm trying to load this certificate:

```
-----BEGIN CERTIFICATE-----
MIIC/jCCAeagAwIBAgIBKjANBgkqhkiG9w0BAQsFADAuMRIwEAYDVQQDDAlNYXN0
ZXIgQ0ExGDAWBgNVBAoMD0NyYWIgd2lkZ2l0cyBTRTAgFw03NTAxMDEwMDAwMDBa
GA80MDk2MDEwMTAwMDAwMFowLjESMBAGA1UEAwwJTWFzdGVyIENBMRgwFgYDVQQK
DA9DcmFiIHdpZGdpdHMgU0UwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDYjmgyV3/LSizJXrYrATZrrPr2Edo8yiOgBLFmi4sgeGdQ5n6nhjTGfBEIP2Ia
6z+hbiGOMncabEBczkdME+JFYVCSkS7r4ivMOzp2egxLgcPKcerBoXI8DUbHhIR9
z89lHiPHDJv3+d0Ac1b9bz9b8OAeZWiQmFvmjpbc2DfhQ2OFx2MwFZCYF196rrXO
c6/SR2esZVRrkW22RBKFTgz6GIA5A/5VWKIISSqEB1gOcMz2iq5987I28+Ez4rcL
Z2lB7cZ7TbNxkAwt0fPL+EuyP7XOzbIj4/kSAlU5xfwNERa3BEuOFro4i5EmSDj+
lR5xdRpFnx0j5zOozUL2lHG9AgMBAAGjJTAjMCEGA1UdEQQaMBiCC2NyYWJzLmNy
YWJzgglsb2NhbGhvc3QwDQYJKoZIhvcNAQELBQADggEBAEp3HQAjMLiXcPqDW+BO
O5Vutm24ccaMEBKoQ3QhEuP9Ck15tA5dIuSNxHjGNIrQ8KBfTxdOEu41oIRzvCCF
4hnDeJArATYM4Nwq+MMVRxavdUj2E1QZ8d4qgJaiUdAIkM12iTpn88TJjBFDsJ29
LWfqbAJj83CscgbeGf7iKV5InEiPZ/MRfpm3fkTsJ8JduI9dTeO51VXy3UpTbxRT
8t+qh9GV549otsYH7m+wvubX7xwQ+wIVy1a57xGEWwWilXqKqnQrccAdc/mPV2O3
JiNzuZmfz+fzvyVxZZXlGb6ny4IqdO7TnkLKzMJxEsR8M+bZa+tdHL7uCNX7u86f
cAo=
-----END CERTIFICATE-----
```

It gives the error `BadParameter`, which is not very informative. The botan CLI tool gives me a much better error: `X509_Certificate parsing failed Time 40960101000000Z does not seem to be valid`.

**Comment by randombit** [comment]
Yeah unfortunately the C API funnels everything down to just an integer error code and all of our useful exception messages etc are lost. I'm not so happy about that either.

The best approach I've been able to come up with would have all the C layer functions returning an error (which is currently an int) would instead return a `botan_error_t*` which is itself an opaque type which can be queried for an error code, error type (eg Bad parameter) and also a string which would capture any exception message, and then we return NULL instead of 0 to indicate success. This would require a few more mallocs etc on error paths but that's probably not a big problem given we are already probably having to do exception handling in the same paths.

However we have to maintain compat with existing code - there are several binding libraries as well as a number of C programs which use the API and the intent is that that API is supported long term. The easiest approach is probably to define a completely new `ffi2` api which uses this new error return type instead of returning ints. Then the existing FFI api is implemented in terms of `ffi2` and just throws away the extra error information, and bindings can be gradually updated (or not) to take advantage of this new error information.

I am for various professional and personal reasons completely swamped right now and don't have time to take on anything in this area but if you were interested in contributing a change along these lines (or something else that improves the situation) I'd be happy to review/assist.

**Comment by est31** [comment]
I just found https://github.com/randombit/botan/blob/2e1540735713d17d4c736ca288765f3e26f03416/src/lib/ffi/ffi.cpp#L22 which should be enough for my purposes. I can absolutely set an env var.

To add an idea, there could be a global variable based method (kinda like errno) to store the error. Access would be possible through a function to retrieve error information, this way one wouldn't need a separate FFI api. It could be implemented by a `thread_local` variable, which are present in C++ since C++11. It seems that botan requires C++11 already, so this shouldn't be an issue? What do you think?

Another approach I thought about was using the C++ API directly, but Rust sadly can't catch C++ errors.

**Comment by randombit** [comment]
@est31 Following up here - in Botan 3 we do have a function which captures the exception string in a `thread_local` and reflects it into the new `Error::error_message` function, so this should be a much more pleasant experience once that version is released and widespread.

Further improvements would be predicated on some changes to the FFI interfaces along the lines I alluded to above. I opened https://github.com/randombit/botan/issues/3356 to track this.
