### ISSUE TITLE
Implement error trait

### ISSUE THREAD

**Issue by dariusc93** [randombit/botan-rs#42]
Some crates generally rely on the use of the error trait within rust when it comes to error handling. Since botan does not implement the trait, this do add abit more work on others end when handling errors with those crates (eg `anyhow`). Considering that you might want to have very little and unnecessary dependencies, doing something like https://github.com/nilbytes/botan-rs/blob/master/botan/src/utils.rs#L139-L146 should be enough (though tad more work might be needed to make it cleaner, add error messages, etc).

Could also be related to #16 (though something like issue that could be done on the developer side than within this crate)

**Comment by randombit** [comment]
I think #16 is unrelated that is more about better exposing the underlying error details via the FFI layer instead of just squashing everything down into a small set of integer error codes.

Your proposal seems fine, thank you for the suggestion. Happy to take a PR for this or I will attend to it at next opportunity.

**Comment by randombit** [comment]
Could you review #43 when you have a moment?

**Comment by dariusc93** [comment]
It looks good to me

**Comment by randombit** [comment]
Merged to master now
