### ISSUE TITLE
All types should be Send and Sync if possible

### ISSUE THREAD

**Issue by teythoon** [randombit/botan-rs#67]
It would be good if the wrapper types would be Send and Sync if possible.  For example, currently the `HashFunction` is neither because it contains a `botan_hash_t` which is a type alias for `*mut botan_hash_struct`, and raw pointers are neither Send nor Sync.

I believe it is safe for `HashFunction` to be Send: the state of the hash function should be safe to transfer between threads (not a C++ expert, but as expected, it looks like numbers and vectors of numbers, nothing that is bound to the current thread in any way).

I believe it is safe for `HashFunction` to be Sync: mutation requires a mutable reference (`update`, `finish`, and `clear` have a mutable receiver in botan-rs 0.9), so it is safe to send an immutable reference to other threads, hence the type is Sync.

Types not being Sync can be worked around by protecting them with a mutex (though at a cost, of course, it'd be better if they were Sync if that is safe).  Types not being Send currently prevents me from using botan-rs.

**Comment by randombit** [comment]
Thanks for pointing this out. I hadn't considered that Rust wouldn't autoimpl `Send` and `Sync` here, though of course that makes sense given the internal pointers.

I can't think of any reason it would not be safe, in this specific instance, to impl `Sync` and `Send` for the various types.

Except that apparently in 0.9 I missed converting some of the receivers from `&self` to `&mut self` - for example `MsgAuthCode::update` still takes `&self`! So that will have to be addressed first.

**Comment by teythoon** [comment]
Sweet, thanks!

**Comment by randombit** [comment]
@teythoon Can you take a look at #68 - this is basically all you are looking for here, right?

**Comment by teythoon** [comment]
Yes, that's exactly what I was hoping for.  Thanks for the quick fix!

**Comment by randombit** [comment]
I just published `botan 0.9.2` to cargo which includes these changes so you should be all set. As I said I am pretty sure these being `Sync`/`Send` is safe but I didn't think about it *that* carefully :sweat_smile:  so if you notice any sort of crashes/UB/etc that indicate a problem in this area please do open an issue.
